In [1]:
import os 
import pandas as pd

In [8]:
raw_data_dir = "data/raw/iuh/IUH DATA/CSV Files/"
processed_data_dir = "data/processed/iuh"

In [3]:
demographics = pd.read_csv(os.path.join(processed_data_dir, "demographics.csv"))
demographics["ArriveDTS"] = pd.to_datetime(demographics["ArriveDTS"])
demographics["DischargeDTS"] = pd.to_datetime(demographics["DischargeDTS"])
demographics

,MRN,FIN,stay_seq,stay_ct_total,DOB,Age_discharge_death,Deceased,Race,Ethnicity,Sex,...,duration_hr,duration_all_hr,FirstArrive,FinalDischarge,ht,wt,bmi_cal,HTN_patient,FacilityLocationCVDSC,Year_info
0,6160,1023527540,1,1,1950-03-28 00:00:00,72.9,NaN,White,Not Hispanic or Latino,Male,...,26.03,26.03,2023-02-07 13:56:00,2023-02-08 15:58:00,182.900,77.600,23.197133,yes,IUH Bedford Hospital,2023
1,36750,943291591,1,1,1947-11-03 00:00:00,74.7,NaN,Black or African American,Not Hispanic or Latino,Female,...,33.87,33.87,2022-07-19 07:55:00,2022-07-20 17:47:00,152.400,67.000,28.847280,yes,IUH University Hospital,2022
2,610960,884200379,1,1,1932-01-01 00:00:00,90.0,2021-12-25 09:20:00,White,Not Hispanic or Latino,Male,...,21.43,21.43,2021-12-24 11:54:00,2021-12-25 09:20:00,170.000,85.600,29.619377,yes,IUH Methodist Hospital,2021
3,773640,848060687,1,1,1957-06-25 00:00:00,64.2,NaN,Black or African American,Not Hispanic or Latino,Male,...,224.08,224.08,2021-08-31 08:25:00,2021-09-09 16:30:00,190.500,106.300,29.291614,yes,IUH University Hospital,2021
4,869540,932914526,1,1,1969-05-27 00:00:00,53.1,NaN,White,Not Hispanic or Latino,Male,...,252.73,252.73,2022-06-23 06:16:00,2022-07-03 19:00:00,190.500,118.900,32.763621,yes,IUH University Hospital,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6940,90012902,986282648,1,1,1944-03-02 00:00:00,78.8,2022-12-07 14:56:00,White,Not Hispanic or Latino,Male,...,3.23,3.23,2022-12-07 11:42:00,2022-12-07 14:56:00,188.000,139.900,39.582390,yes,IUH West Hospital,2022
6941,90013154,1093708244,1,1,1977-12-17 00:00:00,45.8,2023-10-03 12:08:00,Black or African American,Not Hispanic or Latino,Female,...,1.12,1.12,2023-10-03 11:01:00,2023-10-03 12:08:00,157.500,71.400,28.783069,no,IUH Methodist Hospital,2023
6942,90013819,915326300,1,1,1958-10-18 00:00:00,63.5,2022-04-08 20:23:00,White,Not Hispanic or Latino,Female,...,98.25,98.25,2022-04-04 18:08:00,2022-04-08 20:23:00,165.325,61.525,22.509952,yes,IUH Arnett Hospital,2022
6943,90013843,690380837,1,1,1946-05-03 00:00:00,73.6,NaN,White,Not Hispanic or Latino,Female,...,301.00,301.00,2019-11-26 23:15:00,2019-12-09 12:15:00,149.300,57.100,25.616305,yes,IUH Methodist Hospital,2019
6944,90020035,982390262,1,1,1938-10-23 00:00:00,84.2,2023-01-20 00:00:00,White,Not Hispanic or Latino,Female,...,548.57,548.57,2022-11-22 22:14:00,2022-12-15 18:48:00,160.000,61.900,24.179688,yes,IUH Methodist Hospital,2022

In [4]:
demographics.columns

Index(['MRN', 'FIN', 'stay_seq', 'stay_ct_total', 'DOB', 'Age_discharge_death',
       'Deceased', 'Race', 'Ethnicity', 'Sex', 'ArriveDTS', 'DischargeDTS',
       'duration_hr', 'duration_all_hr', 'FirstArrive', 'FinalDischarge', 'ht',
       'wt', 'bmi_cal', 'HTN_patient', 'FacilityLocationCVDSC', 'Year_info'],
      dtype='object')

In [5]:
demographics = demographics[["MRN", "FIN", "Deceased", "DOB", "Race", "Ethnicity", "Sex", "ht", "wt", "bmi_cal", "HTN_patient", "ArriveDTS", "DischargeDTS"]]

In [6]:
demographics["death_status"] = 1
demographics.loc[demographics["Deceased"].isna(), "death_status"] = 0

/tmp/ipykernel_587283/1869496417.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demographics["death_status"] = 1

In [9]:
vitals = pd.read_csv(os.path.join(raw_data_dir, "Vitals.csv"))
vitals["EventDT"] = pd.to_datetime(vitals["EventDT"])
vitals

,MRN,FIN,Event,Result,EventDT
0,10592750,874675606,Heart Rate Monitored,84.0,2021-11-18 09:12:00
1,10592750,874675606,Temperature Route Not Specified,36.9,2021-11-18 09:12:00
2,10592750,874675606,SPO2,99.0,2021-11-18 09:12:00
3,10592750,874675606,Mean Arterial Pressure,NaN,NaT
4,10592750,874675606,Diastolic Blood Pressure,79.0,2021-11-18 09:12:00
...,...,...,...,...,...
5305017,9849840,847680931,"Mean Arterial Pressure, Cuff",83.0,2021-08-27 16:01:00
5305018,9849840,847680931,Temperature Route Not Specified,36.5,2021-08-27 16:01:13
5305019,9849840,847680931,Respiratory Rate,18.0,2021-08-27 16:01:39
5305020,9849840,847680931,Heart Rate Monitored,66.0,2021-08-27 16:01:39
5305021,9849840,847680931,SPO2,98.0,2021-08-27 16:01:39

In [43]:
hr = vitals[vitals["Event"].str.contains("heart rate", case=False)]
hr

              MRN        FIN                 Event  Result             EventDT
0        10592750  874675606  Heart Rate Monitored    84.0 2021-11-18 09:12:00
10       10592750  874675606  Heart Rate Monitored    51.0 2021-11-18 13:58:00
27       10592750  874675606  Heart Rate Monitored    57.0 2021-11-18 18:03:00
36       10592750  874675606  Heart Rate Monitored    57.0 2021-11-18 18:08:00
40       10592750  874675606  Heart Rate Monitored    57.0 2021-11-18 18:15:00
...           ...        ...                   ...     ...                 ...
5304987   9849840  847680931  Heart Rate Monitored    65.0 2021-08-26 23:17:00
5304995   9849840  847680931  Heart Rate Monitored    60.0 2021-08-27 06:10:00
5305003   9849840  847680931  Heart Rate Monitored    82.0 2021-08-27 07:25:45
5305009   9849840  847680931  Heart Rate Monitored    69.0 2021-08-27 12:27:43
5305020   9849840  847680931  Heart Rate Monitored    66.0 2021-08-27 16:01:39

[833798 rows x 5 columns]

In [44]:
sbp = vitals[vitals["Event"].str.contains("systolic blood pressure", case=False)]
sbp

,MRN,FIN,Event,Result,EventDT
6,10592750,874675606,Systolic Blood Pressure,147.0,2021-11-18 09:12:00
11,10592750,874675606,Systolic Blood Pressure,143.0,2021-11-18 13:58:00
30,10592750,874675606,Systolic Blood Pressure,141.0,2021-11-18 18:03:00
33,10592750,874675606,Systolic Blood Pressure,141.0,2021-11-18 18:08:00
42,10592750,874675606,Systolic Blood Pressure,140.0,2021-11-18 18:15:00
...,...,...,...,...,...
5304990,9849840,847680931,Systolic Blood Pressure,117.0,2021-08-27 06:10:00
5304998,9849840,847680931,Systolic Blood Pressure,133.0,2021-08-27 07:25:00
5305005,9849840,847680931,Systolic Blood Pressure,86.0,2021-08-27 12:27:00
5305013,9849840,847680931,Systolic Blood Pressure,100.0,2021-08-27 13:48:00
5305015,9849840,847680931,Systolic Blood Pressure,118.0,2021-08-27 16:01:00

In [46]:
merged_hr = pd.merge(hr, demographics, on=["MRN", "FIN"], how="left")
merged_hr["time_diff"] = merged_hr["EventDT"] - merged_hr["ArriveDTS"]
merged_hr

,MRN,FIN,Event,Result,EventDT,Deceased,DOB,Race,Ethnicity,Sex,ht,wt,bmi_cal,HTN_patient,ArriveDTS,DischargeDTS,death_status,time_diff
0,10592750,874675606,Heart Rate Monitored,84.0,2021-11-18 09:12:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,-1 days +15:15:00
1,10592750,874675606,Heart Rate Monitored,51.0,2021-11-18 13:58:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,-1 days +20:01:00
2,10592750,874675606,Heart Rate Monitored,57.0,2021-11-18 18:03:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:06:00
3,10592750,874675606,Heart Rate Monitored,57.0,2021-11-18 18:08:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:11:00
4,10592750,874675606,Heart Rate Monitored,57.0,2021-11-18 18:15:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836189,9849840,847680931,Heart Rate Monitored,65.0,2021-08-26 23:17:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,8 days 20:07:00
836190,9849840,847680931,Heart Rate Monitored,60.0,2021-08-27 06:10:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 03:00:00
836191,9849840,847680931,Heart Rate Monitored,82.0,2021-08-27 07:25:45,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 04:15:45
836192,9849840,847680931,Heart Rate Monitored,69.0,2021-08-27 12:27:43,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 09:17:43
836193,9849840,847680931,Heart Rate Monitored,66.0,2021-08-27 16:01:39,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 12:51:39

In [47]:
merged_hr.to_csv(os.path.join("data/data_for_training/iuh", "merged_hr_events.csv"), index=False)

In [48]:
merged_sbp = pd.merge(sbp, demographics, on=["MRN", "FIN"], how="left")
merged_sbp["time_diff"] = merged_sbp["EventDT"] - merged_sbp["ArriveDTS"]
merged_sbp

,MRN,FIN,Event,Result,EventDT,Deceased,DOB,Race,Ethnicity,Sex,ht,wt,bmi_cal,HTN_patient,ArriveDTS,DischargeDTS,death_status,time_diff
0,10592750,874675606,Systolic Blood Pressure,147.0,2021-11-18 09:12:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,-1 days +15:15:00
1,10592750,874675606,Systolic Blood Pressure,143.0,2021-11-18 13:58:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,-1 days +20:01:00
2,10592750,874675606,Systolic Blood Pressure,141.0,2021-11-18 18:03:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:06:00
3,10592750,874675606,Systolic Blood Pressure,141.0,2021-11-18 18:08:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:11:00
4,10592750,874675606,Systolic Blood Pressure,140.0,2021-11-18 18:15:00,NaN,1941-09-27 00:00:00,White,Not Hispanic or Latino,Male,175.3,86.0,27.985600,yes,2021-11-18 17:57:00,2021-11-22 19:25:00,0.0,0 days 00:18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749395,9849840,847680931,Systolic Blood Pressure,117.0,2021-08-27 06:10:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 03:00:00
749396,9849840,847680931,Systolic Blood Pressure,133.0,2021-08-27 07:25:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 04:15:00
749397,9849840,847680931,Systolic Blood Pressure,86.0,2021-08-27 12:27:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 09:17:00
749398,9849840,847680931,Systolic Blood Pressure,100.0,2021-08-27 13:48:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 10:38:00
749399,9849840,847680931,Systolic Blood Pressure,118.0,2021-08-27 16:01:00,NaN,1951-03-07 00:00:00,White,Not Hispanic or Latino,Male,177.8,89.2,28.216383,yes,2021-08-18 03:10:00,2021-08-27 20:45:00,0.0,9 days 12:51:00

In [49]:
merged_sbp.to_csv(os.path.join("data/data_for_training/iuh", "merged_sbp_events.csv"), index=False)